export const KEYS = {
  employees:     "att:employees",
  sites:         "att:sites",
  attendance:    "att:attendance",
  rosters:       "att:rosters",
  deductions:    "att:deductions",
  payroll:       "att:payroll",
  ot:            "att:ot",
  companies:     "att:companies",
  quotas:        "att:quotas",
  requirements:  "att:requirements",
  applicants:    "att:applicants",
  leaves:        "att:leaves",
  leaveTimetable:"att:leave-timetable",
};
